#!/bin/sh

WALLDIR="$HOME/Pictures/wallpapers"

random(){
    WALL=`readlink -f "$(fd --type f -e jpg -e png -e jpeg . $WALLDIR | shuf | head -1q)"`
}


if [ ! -z $1 ]
then
    if [ -f $1 ]
    then
        WALL=`readlink -f $1`
    else
        random
    fi
else
    random
fi

echo "wallpaper is $WALL"

wal -i "$WALL"
[ $XDG_SESSION_TYPE = 'x11' ] && xwallpaper --zoom $WALL || swww img --resize crop --transition-step 7 --transition-fps 165 --transition-type simple "$WALL"

echo Setting Wallpaper $WALL

ln -sf "$WALL" ~/.wallpaper.jpg

# My config specific
