#!/bin/sh

filename=/tmp/tesseract-flame.png

QT_SCREEN_SCALE_FACTORS="1;1" XDG_CURRENT_DESKTOP=sway flameshot gui -p $filename
tesseract -l eng+hin+mar --oem 1 $filename stdout | xclip -sel c
rm -f $filename
